### PR TITLE
Optimising Ubuntu Dockerfile

### PR DESCRIPTION
**Pull request by mohitsaxenaknoldus**
I noticed there were some unnecessary image layers so I removed those. Also, removed the stage tag as we don't have multiple stages.

### CODE REVIEW

**Comment by lethal-guitar** [comment]
Thanks! I'll test it when I get a chance 👍🏻

**Comment by mohitsaxenaknoldus** [comment]
> Thanks! I'll test it when I get a chance 👍🏻

Hey, did you get a chance to look at it?

**Comment by lethal-guitar** [comment]
I didn't get around to it yet - I did have a look and it seems reasonable but I didn't have a chance to test it, and that could still take some time before I get to it.

**Comment by lethal-guitar** [comment]
Thanks again 👍🏻

**Pull request merged**
