### PR TITLE
More gamepad support improvements

### LINKED ISSUE #559: Gamepad support: Allow exiting high score entry screen
Right now, the high score entry screen can only be closed using the keyboard. While entering a high score clearly requires a keyboard, it would be good if it's at least possible to leave the screen using a gamepad.

### PR DESCRIPTION
**Pull request by lethal-guitar**
Closes #559

Todo:

* [x] Don't add spacebar to `isConfirmButton`, introduce a separate method instead. Don't want to intercept spacebar for high score entry.

### CODE REVIEW

**Comment by NeonLightning** [comment]
you keep updating and i keep having to recompile lol the struggle. glad to see the gamepad support coming along.

**Comment by lethal-guitar** [comment]
@NeonLightning hehe :grin: Yeah I've got my OGA now and want to make it solid for gamepad-only use. Thanks again for making me aware of that neat little device! Btw, I haven't gotten sound to work yet, is it working for you?

**Comment by NeonLightning** [comment]
what distro are you using? i have sound on both retroroller arch and retroroller void linux. i do see this in the logs though.
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0

**Comment by lethal-guitar** [comment]
I'm using Retroroller Arch, version 20200613a. Interesting, I should look into that..

**Comment by NeonLightning** [comment]
if you want more directly help rather than on here. try the retro game handhelds discord it's retroroller's homebase. the retro arena and emuelec both have their own. and the other distros i think are just on the odroid forums.

**Comment by lethal-guitar** [comment]
Yeah I've been planning to check out the Discord. Will do, thanks!

**Pull request merged**
