### PR TITLE
Fix #479: Merge common/global.hpp into game_logic/global_dependencies.hpp

### LINKED ISSUE #479: Merge `common/global.hpp` into `game_logic/global_dependencies.hpp`
The reasons why this header file lives outside of `game_logic` don't apply anymore. It would make things simpler if it was merged into the other "global" file.

### PR DESCRIPTION
**Pull request by sohamroy19**
Updated `#include`s with correct formatting as well. Fixes #479.

### CODE REVIEW

**Comment by sohamroy19** [comment]
Thanks for the pointers, I'll atleast try to fix it before asking you to :)

**Comment by lethal-guitar** [comment]
@sohamroy19 nice, yes the squashing looks like what I had in mind. But something is odd, you still have your previous commits from before the rebase on your branch, and an empty merge commit? 🤔 We want to end up with only commits  d5b2f9f and 806a429 on this branch. So we want the `git log` to look like this:

```
CLIENT3156 ~/Stuff/RigelEngine/build (merge-redundant-header) $ git log
commit 806a429de336d9f8b3c1128d150eef8ecd06cfda (HEAD -> merge-redundant-header)
Author: royS <72430659+sohamroy19@users.noreply.github.com>
Date:   Sat Oct 9 01:08:58 2021 +0530

    Merge common/global.hpp into game_logic/global_dependencies.hpp
    
    Update #includes & remove common/global.hpp from src/CMakeLists.txt

commit d5b2f9f8d86b3bdd6f3ec9b5b5dfaae4cc61339a
Author: royS <72430659+sohamroy19@users.noreply.github.com>
Date:   Sat Oct 9 03:19:07 2021 +0530

    Added game_logic/global_dependencies.hpp to src/CMakeLists.txt

commit 7e8bdb996618b76db87b0a6d63d34c81a442d76b (sohamroy19/master, origin/master, origin/HEAD)
```

There is a way to invoke the `rebase` command to achieve exactly that - let me know if you'd like to experiment more, or if I should push a new version of the branch 🙂 (and tell you what command I ran to get to that state).

**Comment by sohamroy19** [comment]
Hmmm, seems like I fixed that but went too far back in the `git rebase`.

**Comment by lethal-guitar** [comment]
@sohamroy19 no problem! I force-pushed the branch.

Earlier after your first rebase, I did `git rebase --onto origin/master 4607b7850c` locally, but didn't push the branch yet. That takes all the commits _after_ 4607b7850c and puts them on top of `origin/master`, which then ends up removing the merge commit and all the duplicate history.

With your 2nd rebase, it's a bit harder to fix, but also possible. Let's look at the history in graph form, using a tool like `gitk`:

History

There, we can see that the history splits up into two independent branches after the `fix-wall-dancing` commit, and both of those branches are then combined again with the merge commit at the top of the branch. The two commits that we want to have in this PR are in the middle of the history. We want to have those commits on top of `origin/master` instead, and keep the history linear instead of splitting it up. How could we achieve that?

First, let's reset our branch to commit e07bc3401d, the 2nd one of your commits:

```
git reset --hard e07bc3401d
```

Now, our history looks like this:

image

No more branching, but our commits are still based on an old state. So to fix that, we can now use the `--onto` flag again:

```
git rebase --onto origin/master 5009ab336a12
```

Here, 5009ab336a12 is the commit right before your first commit, i.e. "cmake: Add BUILD_MODDING_TOOLS and BUILD_TESTS".

After that, we end up with the desired end state:

image

Hope that helps! Rebasing can be quite confusing at first, it took me a while to wrap my head around it as well back when I first learned it. I can recommend using a graphical history viewer like `gitk`, it really helps a lot with rebasing.

Not sure what command you ran in the beginning? For interactive rebasing/history rewriting, I usually do: `git rebase -i origin/master`.

**Comment by lethal-guitar** [comment]
Congrats for your first contribution to RigelEngine, and thanks for taking the time! 🎉

**Pull request merged**
