### PR TITLE
Made Viewport consistent throughout

### LINKED ISSUE #795: Consistent spelling: `Viewport` instead of `ViewPort`
Spelling of the word "viewport" is inconsistent in the code, sometimes it's spelled `viewPort` and sometimes `viewport`. It would be nice to make it consistent.

### PR DESCRIPTION
**Pull request by mohitsaxenaknoldus**
Fixes #795

### CODE REVIEW

**Review by lethal-guitar — APPROVED** [review]
Perfect, thanks a lot for your efforts! 👍🏻

**Comment by mohitsaxenaknoldus** [comment]
> Perfect, thanks a lot for your efforts! 👍🏻

Thanks! LMK if you want me to work on any other issue. Is this good for a merge?

**Comment by lethal-guitar** [comment]
> Is this good for a merge?

Yep, looks good, merged it now. Was just doing some final manual testing.

> LMK if you want me to work on any other issue. 

Sure, will do! 🙂 I'll think about what else might be good and maybe create some new issues, I'll ping you if I do.

**Comment by lethal-guitar** [comment]
@mohitsaxenaknoldus I've just added a bunch of new issues tagged `good first issue`, so if you're interested in working on any of these feel free to do so

**Pull request merged**
